### ISSUE TITLE
Cannot get SAML profile

### ISSUE THREAD

**Issue by kalyandas** [pac4j/spring-security-pac4j-boot-demo#3]
I do not get saml profile in the redirected page. Neither SecurityContextHolder.getContext().getAuthentication() returns anything. 
The profile displayed on the index page is [] . Am I doing it wrong ?

**Comment by leleuj** [comment]
By default, you are not authenticated so you will land on the index page without any profile (`http://localhost:8080/`).

Then, I click on "Protected url by SAML2: saml/index.html". I login at Okta.

Finally, I'm back on the "/saml/index.html" page with a profile: `profiles: [#SAML2Profile# | id: testpac4j@gmail.com | attributes: {firstName=[Test], lastName=[pac4j], notOnOrAfter=2017-05-13T08:54:07.589Z, sessionindex=_zmp3byumwdutuvtrq9lucqe5qlrvliygp2ov6zd, notBefore=2017-05-13T08:44:07.589Z} | roles: [] | permissions: [] | isRemembered: false | clientName: SAML2Client | linkedId: null |]`.

Click on "Back" and you'll see the SAML profile on the index page.
