### ISSUE TITLE
internal error on startup

### ISSUE THREAD

**Issue by nogo** [pac4j/spring-security-pac4j-boot-demo#6]
I'm testing this implementation but I get an internal error at startup.

Steps to reproduce:
1. fresh clone of the repository
1. mvn clean compile exec:java
1. open browser al http://127.0.0.1:8080

I get redirected to /auth and see "internal error"

**Comment by leleuj** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
